// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// CookieMiddlewareMock is an autogenerated mock type for the CookieMiddleware type
type CookieMiddlewareMock struct {
	mock.Mock
}

type CookieMiddlewareMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CookieMiddlewareMock) EXPECT() *CookieMiddlewareMock_Expecter {
	return &CookieMiddlewareMock_Expecter{mock: &_m.Mock}
}

// DeleteCookie provides a mock function with given fields: ectx
func (_m *CookieMiddlewareMock) DeleteCookie(ectx echo.Context) {
	_m.Called(ectx)
}

// CookieMiddlewareMock_DeleteCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCookie'
type CookieMiddlewareMock_DeleteCookie_Call struct {
	*mock.Call
}

// DeleteCookie is a helper method to define mock.On call
//   - ectx echo.Context
func (_e *CookieMiddlewareMock_Expecter) DeleteCookie(ectx interface{}) *CookieMiddlewareMock_DeleteCookie_Call {
	return &CookieMiddlewareMock_DeleteCookie_Call{Call: _e.mock.On("DeleteCookie", ectx)}
}

func (_c *CookieMiddlewareMock_DeleteCookie_Call) Run(run func(ectx echo.Context)) *CookieMiddlewareMock_DeleteCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *CookieMiddlewareMock_DeleteCookie_Call) Return() *CookieMiddlewareMock_DeleteCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *CookieMiddlewareMock_DeleteCookie_Call) RunAndReturn(run func(echo.Context)) *CookieMiddlewareMock_DeleteCookie_Call {
	_c.Run(run)
	return _c
}

// GetCookie provides a mock function with given fields: ectx
func (_m *CookieMiddlewareMock) GetCookie(ectx echo.Context) (string, error) {
	ret := _m.Called(ectx)

	if len(ret) == 0 {
		panic("no return value specified for GetCookie")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) (string, error)); ok {
		return rf(ectx)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) string); ok {
		r0 = rf(ectx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(ectx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CookieMiddlewareMock_GetCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCookie'
type CookieMiddlewareMock_GetCookie_Call struct {
	*mock.Call
}

// GetCookie is a helper method to define mock.On call
//   - ectx echo.Context
func (_e *CookieMiddlewareMock_Expecter) GetCookie(ectx interface{}) *CookieMiddlewareMock_GetCookie_Call {
	return &CookieMiddlewareMock_GetCookie_Call{Call: _e.mock.On("GetCookie", ectx)}
}

func (_c *CookieMiddlewareMock_GetCookie_Call) Run(run func(ectx echo.Context)) *CookieMiddlewareMock_GetCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *CookieMiddlewareMock_GetCookie_Call) Return(_a0 string, _a1 error) *CookieMiddlewareMock_GetCookie_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CookieMiddlewareMock_GetCookie_Call) RunAndReturn(run func(echo.Context) (string, error)) *CookieMiddlewareMock_GetCookie_Call {
	_c.Call.Return(run)
	return _c
}

// SetCookie provides a mock function with given fields: ectx, value, maxAge
func (_m *CookieMiddlewareMock) SetCookie(ectx echo.Context, value string, maxAge int) {
	_m.Called(ectx, value, maxAge)
}

// CookieMiddlewareMock_SetCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCookie'
type CookieMiddlewareMock_SetCookie_Call struct {
	*mock.Call
}

// SetCookie is a helper method to define mock.On call
//   - ectx echo.Context
//   - value string
//   - maxAge int
func (_e *CookieMiddlewareMock_Expecter) SetCookie(ectx interface{}, value interface{}, maxAge interface{}) *CookieMiddlewareMock_SetCookie_Call {
	return &CookieMiddlewareMock_SetCookie_Call{Call: _e.mock.On("SetCookie", ectx, value, maxAge)}
}

func (_c *CookieMiddlewareMock_SetCookie_Call) Run(run func(ectx echo.Context, value string, maxAge int)) *CookieMiddlewareMock_SetCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *CookieMiddlewareMock_SetCookie_Call) Return() *CookieMiddlewareMock_SetCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *CookieMiddlewareMock_SetCookie_Call) RunAndReturn(run func(echo.Context, string, int)) *CookieMiddlewareMock_SetCookie_Call {
	_c.Run(run)
	return _c
}

// NewCookieMiddlewareMock creates a new instance of CookieMiddlewareMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCookieMiddlewareMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CookieMiddlewareMock {
	mock := &CookieMiddlewareMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
