// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/aetheris-lab/aetheris-id/api/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// OTPServiceMock is an autogenerated mock type for the OTPService type
type OTPServiceMock struct {
	mock.Mock
}

type OTPServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OTPServiceMock) EXPECT() *OTPServiceMock_Expecter {
	return &OTPServiceMock_Expecter{mock: &_m.Mock}
}

// CreateOTP provides a mock function with given fields: ctx, userID, email
func (_m *OTPServiceMock) CreateOTP(ctx context.Context, userID string, email string) (*entities.OTP, error) {
	ret := _m.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for CreateOTP")
	}

	var r0 *entities.OTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.OTP, error)); ok {
		return rf(ctx, userID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.OTP); ok {
		r0 = rf(ctx, userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OTPServiceMock_CreateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOTP'
type OTPServiceMock_CreateOTP_Call struct {
	*mock.Call
}

// CreateOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
func (_e *OTPServiceMock_Expecter) CreateOTP(ctx interface{}, userID interface{}, email interface{}) *OTPServiceMock_CreateOTP_Call {
	return &OTPServiceMock_CreateOTP_Call{Call: _e.mock.On("CreateOTP", ctx, userID, email)}
}

func (_c *OTPServiceMock_CreateOTP_Call) Run(run func(ctx context.Context, userID string, email string)) *OTPServiceMock_CreateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *OTPServiceMock_CreateOTP_Call) Return(_a0 *entities.OTP, _a1 error) *OTPServiceMock_CreateOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OTPServiceMock_CreateOTP_Call) RunAndReturn(run func(context.Context, string, string) (*entities.OTP, error)) *OTPServiceMock_CreateOTP_Call {
	_c.Call.Return(run)
	return _c
}

// ResendCode provides a mock function with given fields: ctx, otpID
func (_m *OTPServiceMock) ResendCode(ctx context.Context, otpID string) (*entities.OTP, error) {
	ret := _m.Called(ctx, otpID)

	if len(ret) == 0 {
		panic("no return value specified for ResendCode")
	}

	var r0 *entities.OTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.OTP, error)); ok {
		return rf(ctx, otpID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.OTP); ok {
		r0 = rf(ctx, otpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, otpID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OTPServiceMock_ResendCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendCode'
type OTPServiceMock_ResendCode_Call struct {
	*mock.Call
}

// ResendCode is a helper method to define mock.On call
//   - ctx context.Context
//   - otpID string
func (_e *OTPServiceMock_Expecter) ResendCode(ctx interface{}, otpID interface{}) *OTPServiceMock_ResendCode_Call {
	return &OTPServiceMock_ResendCode_Call{Call: _e.mock.On("ResendCode", ctx, otpID)}
}

func (_c *OTPServiceMock_ResendCode_Call) Run(run func(ctx context.Context, otpID string)) *OTPServiceMock_ResendCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OTPServiceMock_ResendCode_Call) Return(_a0 *entities.OTP, _a1 error) *OTPServiceMock_ResendCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OTPServiceMock_ResendCode_Call) RunAndReturn(run func(context.Context, string) (*entities.OTP, error)) *OTPServiceMock_ResendCode_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCode provides a mock function with given fields: ctx, code, otpID
func (_m *OTPServiceMock) ValidateCode(ctx context.Context, code string, otpID string) (*entities.OTP, error) {
	ret := _m.Called(ctx, code, otpID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCode")
	}

	var r0 *entities.OTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.OTP, error)); ok {
		return rf(ctx, code, otpID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.OTP); ok {
		r0 = rf(ctx, code, otpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, otpID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OTPServiceMock_ValidateCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCode'
type OTPServiceMock_ValidateCode_Call struct {
	*mock.Call
}

// ValidateCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - otpID string
func (_e *OTPServiceMock_Expecter) ValidateCode(ctx interface{}, code interface{}, otpID interface{}) *OTPServiceMock_ValidateCode_Call {
	return &OTPServiceMock_ValidateCode_Call{Call: _e.mock.On("ValidateCode", ctx, code, otpID)}
}

func (_c *OTPServiceMock_ValidateCode_Call) Run(run func(ctx context.Context, code string, otpID string)) *OTPServiceMock_ValidateCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *OTPServiceMock_ValidateCode_Call) Return(_a0 *entities.OTP, _a1 error) *OTPServiceMock_ValidateCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OTPServiceMock_ValidateCode_Call) RunAndReturn(run func(context.Context, string, string) (*entities.OTP, error)) *OTPServiceMock_ValidateCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewOTPServiceMock creates a new instance of OTPServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTPServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTPServiceMock {
	mock := &OTPServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
